### PR TITLE
Detect Dokan or WinFSP.  Allow FUSE or non FUSE mode.  Debug logging via config file.

### PR DESCRIPTION
**Pull request by kubilus1**
This should allow three execution modes in Windows:

Dokan-FUSE mode:  DokanyV2 installed.  winfuse enabled in config
WinFSP-FUSE mode:  WinFSP installed.  winfuse enabled
WinFSP-raw mode:  WinFSP installed.  winfuse disabled

Dokan-FUSE would appear to be the fastest mode, and it supports both xp11 and xp12
WinFSP-FUSE is a bit slower and appears to only work on XP12
WinFSP-raw is a tad slower that winfsp-fuse but appears to work on xp11 and xp12, but requires lots of extra maintenance so I'll probably drop this in the future.

### CODE REVIEW

**Comment by alizdavoodi** [comment]
Hey,
Excellent job, Thanks!

There is a problem with updating the default config(`aoconfig.py`). So when I changed the `winfuse = True` in `aoconfig.py` file, the `.autoortho` didn't get the update (even if I removed the file to force it to recreate).
So I just changed the configuration directly in the `.autoortho` file to be able to test this MR.

**Comment by alizdavoodi** [comment]
Could you please define the context of `fastest mode`? By fast, do you mean the initial load time is faster? Or do you mean overall sim functionality is faster?

**Comment by alizdavoodi** [comment]
One of the things that I noticed very fast in this MR, is that when I enabled the debug mode in Dokan-fuse mode, it just logs like crazy! 😆 

```
DEBUG:autoortho_fuse:OPEN: /water_transition.png, 0
DEBUG:autoortho_fuse:OPEN: /water_transition.png, 0
DEBUG:pydds:MipMap(7, 22368384, 22369408, 1024, False, None)
DEBUG:autoortho_fuse:OPEN: FULL PATH: D:\X-Plane 12\Custom Scenery\z_autoortho\_textures\water_transition.png
DEBUG:autoortho_fuse:OPEN: FULL PATH: D:\X-Plane 12\Custom Scenery\z_autoortho\_textures\water_transition.png
DEBUG:pydds:MipMap(8, 22369408, 22369664, 256, False, None)
DEBUG:autoortho_fuse:OPEN: FH= 7
DEBUG:autoortho_fuse:OPEN: FH= 8
DEBUG:pydds:MipMap(9, 22369664, 22369728, 64, False, None)
DEBUG:autoortho_fuse:OPEN: /water_transition.png, 0
DEBUG:pydds:MipMap(10, 22369728, 22369744, 16, False, None)
DEBUG:autoortho_fuse:RELEASE: /22032_34752_BI16.dds
DEBUG:autoortho_fuse:OPEN: FULL PATH: D:\X-Plane 12\Custom Scenery\z_autoortho\_textures\water_transition.png
DEBUG:pydds:22369744
DEBUG:autoortho_fuse:RELEASE DDS: /22032_34752_BI16.dds
DEBUG:autoortho_fuse:OPEN: FH= 9
DEBUG:pydds:11
DEBUG:getortho:Tile: 22016_34752_BI_16 opened for the 2 time.
DEBUG:autoortho_fuse:RELEASE: /water_transition.png
DEBUG:autoortho_fuse:OPEN: FH= 0
DEBUG:autoortho_fuse:OPEN: FH= 0
DEBUG:autoortho_fuse:OPEN: FH= 0
DEBUG:autoortho_fuse:OPEN: FH= 0
DEBUG:getortho:Still have 3 refs for 22048_34752_BI_16
DEBUG:autoortho_fuse:GETATTR /water_transition.dds
DEBUG:autoortho_fuse:OPEN: /22048_34768_BI16.dds, 0
DEBUG:autoortho_fuse:RELEASE: /water_transition.png
DEBUG:autoortho_fuse:RELEASE: /water_transition.png
DEBUG:autoortho_fuse:RELEASE: /water_transition.png
DEBUG:getortho:Still have 2 refs for 22048_34752_BI_16
DEBUG:autoortho_fuse:RELEASE: /water_transition.png
DEBUG:autoortho_fuse:GETATTR FULLPATH D:\X-Plane 12\Custom Scenery\z_autoortho\_textures\water_transition.dds  Exists? False
DEBUG:autoortho_fuse:OPEN: FULL PATH: D:\X-Plane 12\Custom Scenery\z_autoortho\_textures\22048_34768_BI16.dds
DEBUG:autoortho_fuse:RELEASE: /water_transition.png
DEBUG:autoortho_fuse:RELEASE: /22016_34752_BI16.dds
DEBUG:autoortho_fuse:RELEASE: /22016_34752_BI16.dds
DEBUG:autoortho_fuse:RELEASE: /22016_34752_BI16.dds
DEBUG:pydds:MipMap(0, 128, 16777344, 16777216, False, None)
DEBUG:fuse:FUSE operation getattr raised a <class 'FileNotFoundError'>, returning errno 2.
Traceback (most recent call last):
  File "C:\Users\alizdavooodi\AppData\Roaming\Python\Python310\site-packages\fuse.py", line 734, in _wrapper
    return func(*args, **kwargs) or 0
  File "C:\Users\alizdavooodi\AppData\Roaming\Python\Python310\site-packages\fuse.py", line 774, in getattr
    return self.fgetattr(path, buf, None)
  File "C:\Users\alizdavooodi\AppData\Roaming\Python\Python310\site-packages\fuse.py", line 1027, in fgetattr
    attrs = self.operations('getattr', self._decode_optional_path(path), fh)
  File "C:\Users\alizdavooodi\AppData\Roaming\Python\Python310\site-packages\fuse.py", line 1076, in __call__
    return getattr(self, op)(*args)
  File "D:\autoortho-code\autoortho\autoortho_fuse.py", line 165, in getattr
    st = os.lstat(full_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\X-Plane 12\\Custom Scenery\\z_autoortho\\_textures\\water_transition.dds'
DEBUG:autoortho_fuse:RELEASE: /22016_34752_BI16.dds
DEBUG:getortho:Get_tile: 22048_34768_BI_16
DEBUG:autoortho_fuse:RELEASE DDS: /22016_34752_BI16.dds
DEBUG:autoortho_fuse:GETATTR /water_transition.dds
DEBUG:autoortho_fuse:RELEASE DDS: /22016_34752_BI16.dds
DEBUG:autoortho_fuse:RELEASE DDS: /22016_34752_BI16.dds
DEBUG:pydds:MipMap(1, 16777344, 20971648, 4194304, False, None)
DEBUG:autoortho_fuse:GETATTR /water_transition.dds
DEBUG:autoortho_fuse:RELEASE DDS: /22016_34752_BI16.dds
DEBUG:autoortho_fuse:GETATTR FULLPATH D:\X-Plane 12\Custom Scenery\z_autoortho\_textures\water_transition.dds  Exists? False
DEBUG:pydds:MipMap(2, 20971648, 22020224, 1048576, False, None)
DEBUG:autoortho_fuse:GETATTR FULLPATH D:\X-Plane 12\Custom Scenery\z_autoortho\_textures\water_transition.dds  Exists? False
DEBUG:fuse:FUSE operation getattr raised a <class 'FileNotFoundError'>, returning errno 2.
Traceback (most recent call last):
  File "C:\Users\alizdavooodi\AppData\Roaming\Python\Python310\site-packages\fuse.py", line 734, in _wrapper
    return func(*args, **kwargs) or 0
  File "C:\Users\alizdavooodi\AppData\Roaming\Python\Python310\site-packages\fuse.py", line 774, in getattr
    return self.fgetattr(path, buf, None)
  File "C:\Users\alizdavooodi\AppData\Roaming\Python\Python310\site-packages\fuse.py", line 1027, in fgetattr
    attrs = self.operations('getattr', self._decode_optional_path(path), fh)
  File "C:\Users\alizdavooodi\AppData\Roaming\Python\Python310\site-packages\fuse.py", line 1076, in __call__
    return getattr(self, op)(*args)
  File "D:\autoortho-code\autoortho\autoortho_fuse.py", line 165, in getattr
    st = os.lstat(full_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\X-Plane 12\\Custom Scenery\\z_autoortho\\_textures\\water_transition.dds'
DEBUG:pydds:MipMap(3, 22020224, 22282368, 262144, False, None)
DEBUG:fuse:FUSE operation getattr raised a <class 'FileNotFoundError'>, returning errno 2.
```

**Comment by alizdavoodi** [comment]
After the sim load completed, I did get a lot of `flight disconnect` error:

```
DEBUG:flighttrack:Lat: 50.04091262817383, Lon: 8.5575532913208, Alt: -0.010610485449433327
INFO:flighttrack:FT: Flight disconnected.
DEBUG:flighttrack:Socket timeout.  Reset.
DEBUG:flighttrack:Socket timeout.  Reset.
INFO:aostats:STATS: ID: {'partial_mm': 22796, 'count': 189926, 'chunk_miss': 158028, 'bytes_dl': 2273748913, 'mm_counts': {0: 433, 1: 22, 2: 54, 3: 120, 4: 4315}, 'mm_averages': {0: 0.15, 1: 0.07, 2: 0.04, 3: 0.03, 4: 0.06}, 'chunk_hit': 31898, 'minutes_to_start': 0.01}
INFO:flighttrack:FT: Flight is starting.
INFO:flighttrack:FT: Time to start was 0.01 minutes.
DEBUG:flighttrack:Lat: 50.04091262817383, Lon: 8.5575532913208, Alt: -0.010572153143584728
INFO:flighttrack:FT: Flight disconnected.
DEBUG:flighttrack:Socket timeout.  Reset.
DEBUG:flighttrack:Socket timeout.  Reset.
INFO:flighttrack:FT: Flight is starting.
INFO:flighttrack:FT: Time to start was 0.01 minutes.
DEBUG:flighttrack:Lat: 50.04091262817383, Lon: 8.5575532913208, Alt: -0.01060592569410801
INFO:flighttrack:FT: Flight disconnected.
DEBUG:flighttrack:Socket timeout.  Reset.
DEBUG:flighttrack:Socket timeout.  Reset.
DEBUG:flighttrack:Socket timeout.  Reset.
INFO:flighttrack:FT: Flight is starting.
INFO:flighttrack:FT: Time to start was 0.01 minutes.
DEBUG:flighttrack:Lat: 50.04091262817383, Lon: 8.5575532913208, Alt: -0.010647766292095184
INFO:flighttrack:FT: Flight disconnected.
DEBUG:flighttrack:Socket timeout.  Reset.
INFO:flighttrack:FT: Flight is starting.
INFO:flighttrack:FT: Time to start was 0.01 minutes.
DEBUG:flighttrack:Lat: 50.04091262817383, Lon: 8.5575532913208, Alt: -0.01067289523780346
INFO:flighttrack:FT: Flight disconnected.
DEBUG:flighttrack:Socket timeout.  Reset.
DEBUG:flighttrack:Socket timeout.  Reset.
DEBUG:flighttrack:Socket timeout.  Reset.
INFO:flighttrack:FT: Flight is starting.
INFO:flighttrack:FT: Time to start was 0.02 minutes.
DEBUG:flighttrack:Lat: 50.04091262817383, Lon: 8.5575532913208, Alt: -0.010657181032001972
INFO:flighttrack:FT: Flight disconnected.
DEBUG:flighttrack:Socket timeout.  Reset.
DEBUG:flighttrack:Socket timeout.  Reset.
```

**Comment by kubilus1** [comment]
> Hey, Excellent job, Thanks!
> 
> There is a problem with updating the default config(`aoconfig.py`). So when I changed the `winfuse = True` in `aoconfig.py` file, the `.autoortho` didn't get the update (even if I removed the file to force it to recreate). So I just changed the configuration directly in the `.autoortho` file to be able to test this MR.

The intention is to edit the .autoortho config file.  The python aoconfig.py are just the defaults so that won't overwrite settings, so this is working as intended.

**Comment by kubilus1** [comment]
As far as perf, I can measure things a few ways.  XPlane start time alone can have a lot of X factors so it's not the best test.  It's also not the only perf concern.

If you isolate and look at the amount of pixel throughput when processing DDS files,  Dokan on my system gives around 10MBps whereas WinFSP caps out at around 8MBps.

More dramatically, if I look at response rates using locust Dokan is around 45 RPS on my system with an average response rate of about 4ms wheres WinFSP is really terrible around 3.5RPS (!) and a response rate around 300ms.  Which is just terrible.  This probably contributes significantly to not so much the start time, but the time it take for the scenery processing to keep up while you fly.  Also likely stuttering.

**Comment by alizdavoodi** [comment]
I see your point,
So the pref measurement it's more than just simple as a start time.

With Dokan, I got `INFO:flighttrack:FT: Time to start was 7.94 minutes.`

**Comment by alizdavoodi** [comment]
I tried to read the code to find the logic behind these logs 🤔  but I don't understand.
```
INFO:flighttrack:FT: Flight is starting.
INFO:flighttrack:FT: Time to start was 0.01 minutes.
INFO:flighttrack:FT: Flight disconnected.
INFO:flighttrack:FT: Flight is starting.
INFO:flighttrack:FT: Time to start was 0.01 minutes.
INFO:flighttrack:FT: Flight disconnected.
INFO:flighttrack:FT: Flight is starting.
INFO:flighttrack:FT: Time to start was 0.01 minutes.
INFO:flighttrack:FT: Flight disconnected.
INFO:flighttrack:FT: Flight is starting.
INFO:flighttrack:FT: Time to start was 0.01 minutes.
INFO:flighttrack:FT: Flight disconnected.
INFO:flighttrack:FT: Flight is starting.
INFO:flighttrack:FT: Time to start was 0.02 minutes.
```

Why do I get continuously disconnect/connect logs?

**Comment by kubilus1** [comment]
It's the XPlane UDP stat connection timing out.  Maybe that's setup
non-standard on your system or this is when you have the sim paused or
something?  Shouldn't really affect anything.

**Comment by alizdavoodi** [comment]
Check. (I can confirm, as you mentioned it doesn't affect anything).

What about these warnings?
```
WARNING:getortho:TILE: Tile(34560, 22928, BI, 16, 12, C:\Users\alizdavooodi\.autoortho-data\cache) retrieved mipmap 0, but only read 5335600.
```

**Comment by kubilus1** [comment]
That right there is the entire crux of why Windows is so slow to initially
load things.  The FS calls seem to be extremely wasteful.  Doesn't happen
on Linux.  It could come down to Windows will just always be 3-4 times
slower than other OS's.

**Comment by alizdavoodi** [comment]
Indeed!
I've tried it on NixOS (Linux), and it's much faster than Windows 10 😕

**Pull request merged**
