### PR TITLE
Fix error when ortho dirs are completely or partially missing

### PR DESCRIPTION
**Pull request by marangonico**

### CODE REVIEW

**Review by kubilus1 — COMMENTED** [review]
Thanks for the PR, good idea to check for this.  I have a suggestion, though.

**Review by marangonico — COMMENTED** [review]
I like both ways, and exceptions show elegance sometimes :-)
p.s. you are missing an "if".

**Comment by kubilus1** [comment]
> I like both ways, and exceptions show elegance sometimes :-) p.s. you are missing an "if".

lol.  Indeed I was.   Updated!

**Review by kubilus1 — APPROVED** [review]
LGTM

**Pull request merged**
